test_homepage:
    path:     /test
    defaults: { _controller: TestBundle:Default:index }

test_form:
    path:     /form
    defaults: { _controller: TestBundle:Default:formulario }

test_form_p:
    path:     /formProd
    defaults: { _controller: TestBundle:Default:formularioProductos }
