test_homepage:
    path:     /test
    defaults: { _controller: TestBundle:Default:index }
test_form:
    path:     /form
    defaults: { _controller: TestBundle:Default:formulario }

test_form_p:
    path:     /formProd
    defaults: { _controller: TestBundle:Default:formularioProductos }

test_get_products:
    path:     /get-products/{id}
    methods: [GET]
    defaults: { _controller: TestBundle:Default:getProducts, id: 0 }

test_add_product:
    path:     /add-products
    methods: [POST]
    defaults: { _controller: TestBundle:Default:addProduct }

test_update_product:
    path:     /product/update
    methods: [POST]
    defaults: { _controller: TestBundle:Default:updateProduct }

