test_homepage:
    path:     /test
    defaults: { _controller: TestBundle:Default:index }
test_form:
    path:     /form
    defaults: { _controller: TestBundle:Default:formulario }

test_form_p:
    path:     /formProd
    defaults: { _controller: TestBundle:Default:formularioProductos }

test_get_products:
    path:     /get-products/{id}
    methods: [GET]
    defaults: { _controller: TestBundle:Default:getProducts, id: 0 }

test_add_product:
    path:     /add-products
    methods: [POST]
    defaults: { _controller: TestBundle:Default:addProduct }

test_update_product:
    path:     /product/update
    methods: [POST]
    defaults: { _controller: TestBundle:Default:updateProduct }

test_delete_product:
    path:     /product/delete
    methods: [POST]
    defaults: { _controller: TestBundle:Default:deleteProduct }


test_get_users:
    path:     /get-users/{id}
    methods: [GET]
    defaults: { _controller: TestBundle:Default:getUsers, id: 0 }

test_add_user:
    path:     /add-users
    methods: [POST]
    defaults: { _controller: TestBundle:Default:addUser }

test_update_user:
    path:     /user/update
    methods: [POST]
    defaults: { _controller: TestBundle:Default:updateUser }

test_delete_user:
    path:     /user/delete
    methods: [POST]
    defaults: { _controller: TestBundle:Default:deleteUser }


