test_homepage:
    path:     /test
    defaults: { _controller: TestBundle:Default:index }

test_homepage_get_products:
    path:     /get-products/{id}
    methods: [GET]
    defaults: { _controller: TestBundle:Default:getProducts, id: 0 }
