user_homepage:
    path:     /usuario
    defaults: { _controller: UserBundle:Default:index }

test_form_p:
    path:     /formProd
    defaults: { _controller: UserBundle:Default:formularioUser }

test_get_user:
    path:     /get-user/{id}
    methods: [GET]
    defaults: { _controller: UserBundle:Default:getUser, id: 0 }
    
test_add_User:
    path:     /add-Users
    methods: [POST]
    defaults: { _controller: UserBundle:Default:addUsuario }

test_update_User:
    path:     /User/update
    methods: [POST]
    defaults: { _controller: UserBundle:Default:updateUser }

test_delete_User:
    path:     /User/eliminar
    methods: [POST]
    defaults: { _controller: UserBundle:Default:eliminarUser }

